/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.table.*;
import java.awt.*;
import EDD.Lista;
import models.*;
import filesystem.*;
import process.GestorProcesos;
import schedulers.*;
import persistence.GestorPersistencia;

/**
 * Ventana principal del simulador de sistema de archivos - Versión con diseñador NetBeans
 * @author susov
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // Componentes principales del sistema
    private SimuladorDisco disco;
    private GestorArchivos gestorArchivos;
    private GestorProcesos gestorProcesos;
    private PlanificadorDisco[] planificadores;

    // Modelo de datos para componentes visuales
    private DefaultTreeModel modeloArbol;
    private DefaultMutableTreeNode nodoRaiz;
    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloTablaFAT;
    private DefaultTableModel modeloTablaProcesos;
    private DefaultTableModel modeloTablaColaIO;

    // Panel personalizado para dibujar el disco
    private JPanel panelDisco;

    // Timer para simulación
    private Timer timerSimulacion;
    private boolean simulacionActiva = false;

    /**
     * Creates new form VentanaPrincipalForm
     */
    public VentanaPrincipal() {
        initComponents();
        inicializarSistema();
        //actualizarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContextual = new javax.swing.JPopupMenu();
        menuCrearArchivo = new javax.swing.JMenuItem();
        menuCrearDir = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        menuEliminar = new javax.swing.JMenuItem();
        menuRenombrar = new javax.swing.JMenuItem();
        panelPrincipal = new javax.swing.JPanel();
        panelControles = new javax.swing.JPanel();
        btnModoAdmin = new javax.swing.JToggleButton();
        lblPlanificador = new javax.swing.JLabel();
        comboPlanificador = new javax.swing.JComboBox<>();
        btnCrearDirectorio = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        lblVelocidad = new javax.swing.JLabel();
        sliderVelocidad = new javax.swing.JSlider();
        btnGuardar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        splitPrincipal = new javax.swing.JSplitPane();
        splitIzquierdo = new javax.swing.JSplitPane();
        panelArbol = new javax.swing.JPanel();
        scrollArbol = new javax.swing.JScrollPane();
        treeArchivos = new javax.swing.JTree();
        panelInfo = new javax.swing.JPanel();
        lblInfoNombre = new javax.swing.JLabel();
        lblInfoTipo = new javax.swing.JLabel();
        lblInfoUbicacion = new javax.swing.JLabel();
        lblInfoDetalles1 = new javax.swing.JLabel();
        lblInfoDetalles2 = new javax.swing.JLabel();
        lblInfoCadenaBLK = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        splitCentral = new javax.swing.JSplitPane();
        panelDiscoContainer = new javax.swing.JPanel();
        panelTablas = new javax.swing.JPanel();
        scrollAsignacion = new javax.swing.JScrollPane();
        tableAsignacion = new javax.swing.JTable();
        scrollFAT = new javax.swing.JScrollPane();
        tableFAT = new javax.swing.JTable();
        panelDerecho = new javax.swing.JPanel();
        panelBotonesProcesos = new javax.swing.JPanel();
        btnCrearProceso = new javax.swing.JButton();
        btnCrear10Procesos = new javax.swing.JButton();
        splitProcesos = new javax.swing.JSplitPane();
        scrollProcesos = new javax.swing.JScrollPane();
        tableProcesos = new javax.swing.JTable();
        scrollColaIO = new javax.swing.JScrollPane();
        tableColaIO = new javax.swing.JTable();
        panelEstadisticas = new javax.swing.JPanel();
        lblPlanificadorActual = new javax.swing.JLabel();
        lblSolicitudesAtendidas = new javax.swing.JLabel();
        lblMovimientosTotales = new javax.swing.JLabel();
        lblPromedioMovimientos = new javax.swing.JLabel();
        lblSolicitudesPendientes = new javax.swing.JLabel();
        panelEstado = new javax.swing.JPanel();
        lblEstadoDisco = new javax.swing.JLabel();
        lblCabezaDisco = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        menuCrearArchivo.setText("Crear Archivo");
        menuCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearArchivoActionPerformed(evt);
            }
        });
        menuContextual.add(menuCrearArchivo);

        menuCrearDir.setText("Crear Directorio");
        menuCrearDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearDirActionPerformed(evt);
            }
        });
        menuContextual.add(menuCrearDir);
        menuContextual.add(separator1);

        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        menuContextual.add(menuEliminar);

        menuRenombrar.setText("Renombrar");
        menuRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRenombrarActionPerformed(evt);
            }
        });
        menuContextual.add(menuRenombrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Sistema de Archivos - Proyecto SO2");

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        panelControles.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));

        btnModoAdmin.setSelected(true);
        btnModoAdmin.setText("Modo: Administrador");
        btnModoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoAdminActionPerformed(evt);
            }
        });

        lblPlanificador.setText("Planificador:");

        comboPlanificador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));
        comboPlanificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPlanificadorActionPerformed(evt);
            }
        });

        btnCrearDirectorio.setText("Crear Directorio");
        btnCrearDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDirectorioActionPerformed(evt);
            }
        });

        btnSimular.setText("▶ Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        lblVelocidad.setText("Velocidad:");

        sliderVelocidad.setInverted(true);
        sliderVelocidad.setMaximum(1000);
        sliderVelocidad.setMinimum(50);
        sliderVelocidad.setValue(500);
        sliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVelocidadStateChanged(evt);
            }
        });

        btnGuardar.setText("💾 Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCargar.setText("📂 Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("🗑 Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPlanificador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearDirectorio)
                .addGap(18, 18, 18)
                .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVelocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModoAdmin)
                    .addComponent(lblPlanificador)
                    .addComponent(comboPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearDirectorio)
                    .addComponent(btnSimular)
                    .addComponent(lblVelocidad)
                    .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCargar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPrincipal.setDividerLocation(900);

        splitIzquierdo.setDividerLocation(250);

        panelArbol.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Archivos"));

        treeArchivos.setComponentPopupMenu(menuContextual);
        treeArchivos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeArchivosValueChanged(evt);
            }
        });
        scrollArbol.setViewportView(treeArchivos);

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        lblInfoNombre.setText("Seleccione un elemento");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoDetalles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoDetalles2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoCadenaBLK, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoDetalles1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoDetalles2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoCadenaBLK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelArbolLayout = new javax.swing.GroupLayout(panelArbol);
        panelArbol.setLayout(panelArbolLayout);
        panelArbolLayout.setHorizontalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelArbolLayout.setVerticalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArbolLayout.createSequentialGroup()
                .addComponent(scrollArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitIzquierdo.setLeftComponent(panelArbol);

        splitCentral.setDividerLocation(250);
        splitCentral.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelDiscoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulación del Disco (SD)"));
        panelDiscoContainer.setLayout(new java.awt.BorderLayout());
        splitCentral.setTopComponent(panelDiscoContainer);

        scrollAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Asignación de Archivos"));

        tableAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollAsignacion.setViewportView(tableAsignacion);

        scrollFAT.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla FAT (File Allocation Table)"));

        tableFAT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollFAT.setViewportView(tableFAT);

        javax.swing.GroupLayout panelTablasLayout = new javax.swing.GroupLayout(panelTablas);
        panelTablas.setLayout(panelTablasLayout);
        panelTablasLayout.setHorizontalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollAsignacion)
            .addComponent(scrollFAT)
        );
        panelTablasLayout.setVerticalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addComponent(scrollAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollFAT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitCentral.setBottomComponent(panelTablas);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitCentral)
        );

        splitIzquierdo.setRightComponent(panelCentral);

        splitPrincipal.setLeftComponent(splitIzquierdo);

        panelDerecho.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Procesos"));
        panelDerecho.setPreferredSize(new java.awt.Dimension(350, 0));

        btnCrearProceso.setText("+ Crear Proceso");
        btnCrearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProcesoActionPerformed(evt);
            }
        });

        btnCrear10Procesos.setText("+ Crear 10 Aleatorios");
        btnCrear10Procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear10ProcesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesProcesosLayout = new javax.swing.GroupLayout(panelBotonesProcesos);
        panelBotonesProcesos.setLayout(panelBotonesProcesosLayout);
        panelBotonesProcesosLayout.setHorizontalGroup(
            panelBotonesProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesProcesosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrear10Procesos)
                .addContainerGap())
        );
        panelBotonesProcesosLayout.setVerticalGroup(
            panelBotonesProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProceso)
                    .addComponent(btnCrear10Procesos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitProcesos.setDividerLocation(250);
        splitProcesos.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitProcesos.setResizeWeight(0.6);

        scrollProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        tableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollProcesos.setViewportView(tableProcesos);

        splitProcesos.setTopComponent(scrollProcesos);

        scrollColaIO.setBorder(javax.swing.BorderFactory.createTitledBorder("Cola de I/O del Disco"));

        tableColaIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollColaIO.setViewportView(tableColaIO);

        splitProcesos.setBottomComponent(scrollColaIO);

        panelEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas"));

        lblPlanificadorActual.setText("Planificador: FIFO");

        lblSolicitudesAtendidas.setText("Solicitudes atendidas: 0");

        lblMovimientosTotales.setText("Movimientos totales: 0");

        lblPromedioMovimientos.setText("Promedio mov/solicitud: 0.0");

        lblSolicitudesPendientes.setText("Solicitudes pendientes: 0");

        javax.swing.GroupLayout panelEstadisticasLayout = new javax.swing.GroupLayout(panelEstadisticas);
        panelEstadisticas.setLayout(panelEstadisticasLayout);
        panelEstadisticasLayout.setHorizontalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlanificadorActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSolicitudesAtendidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovimientosTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPromedioMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSolicitudesPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEstadisticasLayout.setVerticalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlanificadorActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSolicitudesAtendidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMovimientosTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromedioMovimientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSolicitudesPendientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonesProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(splitProcesos)
            .addComponent(panelEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addComponent(panelBotonesProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPrincipal.setRightComponent(panelDerecho);

        panelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEstadoDisco.setText("Disco: 0/100 bloques ocupados (0%)");

        lblCabezaDisco.setText("Cabeza en bloque: 0");

        lblUsuario.setText("Usuario: admin");

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstadoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCabezaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoDisco)
                    .addComponent(lblCabezaDisco)
                    .addComponent(lblUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(splitPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
            .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ========== MÉTODOS DE EVENT HANDLERS ==========
    
    private void btnModoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoAdminActionPerformed
        boolean esAdmin = btnModoAdmin.isSelected();
        gestorArchivos.setModoAdministrador(esAdmin);
        btnModoAdmin.setText(esAdmin ? "Modo: Administrador" : "Modo: Usuario");
    }//GEN-LAST:event_btnModoAdminActionPerformed

    private void comboPlanificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPlanificadorActionPerformed
        int index = comboPlanificador.getSelectedIndex();
        gestorProcesos.cambiarPlanificador(planificadores[index]);
        lblPlanificadorActual.setText("Planificador: " + planificadores[index].getNombre());
    }//GEN-LAST:event_comboPlanificadorActionPerformed

    private void btnCrearDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDirectorioActionPerformed
        mostrarDialogoCrearDirectorio();
    }//GEN-LAST:event_btnCrearDirectorioActionPerformed

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        simulacionActiva = !simulacionActiva;
        if (simulacionActiva) {
            timerSimulacion.start();
            btnSimular.setText("⏹ Detener");
        } else {
            timerSimulacion.stop();
            btnSimular.setText("▶ Simular");
        }
    }//GEN-LAST:event_btnSimularActionPerformed

    private void sliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadStateChanged
        int delay = sliderVelocidad.getValue();
        timerSimulacion.setDelay(delay);
    }//GEN-LAST:event_sliderVelocidadStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
         
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void treeArchivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeArchivosValueChanged
        
    }//GEN-LAST:event_treeArchivosValueChanged

    private void menuCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearArchivoActionPerformed
        
    }//GEN-LAST:event_menuCrearArchivoActionPerformed

    private void menuCrearDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearDirActionPerformed
       
    }//GEN-LAST:event_menuCrearDirActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
       
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void menuRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRenombrarActionPerformed
        
    }//GEN-LAST:event_menuRenombrarActionPerformed

    private void btnCrearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProcesoActionPerformed
        
    }//GEN-LAST:event_btnCrearProcesoActionPerformed

    private void btnCrear10ProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear10ProcesosActionPerformed
        
    }//GEN-LAST:event_btnCrear10ProcesosActionPerformed


    
    private void inicializarSistema() {
        disco = new SimuladorDisco();
        gestorArchivos = new GestorArchivos(disco);
        gestorProcesos = new GestorProcesos();
        
        gestorProcesos.configurarSistemaArchivos(gestorArchivos, disco);
        
        planificadores = new PlanificadorDisco[] {
            new FIFO(),
            new SSTF(),
            new SCAN(),
            new CSCAN()
        };
    }
    

    
    private void mostrarDialogoCrearArchivo() {
        if (!gestorArchivos.isModoAdministrador()) {
            JOptionPane.showMessageDialog(this, "Solo administradores pueden crear archivos",
                    "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JPanel panel = new JPanel(new GridLayout(2, 2, 5, 5));
        JTextField txtNombre = new JTextField();
        JSpinner spnBloques = new JSpinner(new SpinnerNumberModel(1, 1, 50, 1));

        panel.add(new JLabel("Nombre del archivo:"));
        panel.add(txtNombre);
        panel.add(new JLabel("Tamaño (bloques):"));
        panel.add(spnBloques);

        int result = JOptionPane.showConfirmDialog(this, panel, "Crear Archivo",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION && !txtNombre.getText().trim().isEmpty()) {
            navegarADirectorioSeleccionado();
            boolean exito = gestorArchivos.crearArchivo(txtNombre.getText().trim(),
                    (Integer) spnBloques.getValue());
            if (exito) {
                //actualizarTodo();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el archivo",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void mostrarDialogoCrearDirectorio() {
        if (!gestorArchivos.isModoAdministrador()) {
            JOptionPane.showMessageDialog(this, "Solo administradores pueden crear directorios",
                    "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = JOptionPane.showInputDialog(this, "Nombre del directorio:",
                "Crear Directorio", JOptionPane.PLAIN_MESSAGE);

        if (nombre != null && !nombre.trim().isEmpty()) {
            navegarADirectorioSeleccionado();
            boolean exito = gestorArchivos.crearDirectorio(nombre.trim());
            if (exito) {
                //actualizarTodo();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el directorio",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void eliminarSeleccionado() {
        if (!gestorArchivos.isModoAdministrador()) {
            JOptionPane.showMessageDialog(this, "Solo administradores pueden eliminar",
                    "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TreePath path = treeArchivos.getSelectionPath();
        if (path == null || path.getPathCount() <= 1) {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento para eliminar",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) path.getLastPathComponent();
        Object objeto = nodo.getUserObject();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar '" + objeto + "'?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            navegarADirectorioPadreSeleccionado();

            if (objeto instanceof Archivo) {
                gestorArchivos.eliminarArchivo(((Archivo) objeto).getNombre());
            } else if (objeto instanceof Directorio) {
                gestorArchivos.eliminarDirectorio(((Directorio) objeto).getNombre());
            }

            //actualizarTodo();
        }
    }

    private void renombrarSeleccionado() {
        if (!gestorArchivos.isModoAdministrador()) {
            JOptionPane.showMessageDialog(this, "Solo administradores pueden renombrar",
                    "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TreePath path = treeArchivos.getSelectionPath();
        if (path == null || path.getPathCount() <= 1) {
            return;
        }

        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) path.getLastPathComponent();
        Object objeto = nodo.getUserObject();

        String nombreActual = objeto.toString();
        String nuevoNombre = JOptionPane.showInputDialog(this, "Nuevo nombre:", nombreActual);

        if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
            navegarADirectorioPadreSeleccionado();

            if (objeto instanceof Archivo) {
                gestorArchivos.renombrarArchivo(nombreActual, nuevoNombre.trim());
            } else if (objeto instanceof Directorio) {
                gestorArchivos.renombrarDirectorio(nombreActual, nuevoNombre.trim());
            }

            //actualizarTodo();
        }
    }

    private void navegarADirectorioSeleccionado() {
        TreePath path = treeArchivos.getSelectionPath();
        gestorArchivos.irARaiz();

        if (path != null) {
            for (int i = 1; i < path.getPathCount(); i++) {
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) path.getPathComponent(i);
                Object obj = nodo.getUserObject();
                if (obj instanceof Directorio) {
                    gestorArchivos.entrarDirectorio(((Directorio) obj).getNombre());
                }
            }
        }
    }

    private void navegarADirectorioPadreSeleccionado() {
        TreePath path = treeArchivos.getSelectionPath();
        gestorArchivos.irARaiz();

        if (path != null && path.getPathCount() > 2) {
            for (int i = 1; i < path.getPathCount() - 1; i++) {
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) path.getPathComponent(i);
                Object obj = nodo.getUserObject();
                if (obj instanceof Directorio) {
                    gestorArchivos.entrarDirectorio(((Directorio) obj).getNombre());
                }
            }
        }
    }

    private void mostrarInfoSeleccionado() {
        TreePath path = treeArchivos.getSelectionPath();

        if (path == null) {
            lblInfoNombre.setText("Seleccione un elemento");
            lblInfoTipo.setText("");
            lblInfoUbicacion.setText("");
            lblInfoDetalles1.setText("");
            lblInfoDetalles2.setText("");
            lblInfoCadenaBLK.setText("");
            return;
        }

        StringBuilder ubicacion = new StringBuilder();
        for (int i = 0; i < path.getPathCount() - 1; i++) {
            DefaultMutableTreeNode nodoPath = (DefaultMutableTreeNode) path.getPathComponent(i);
            Object obj = nodoPath.getUserObject();
            if (obj instanceof Directorio) {
                Directorio d = (Directorio) obj;
                if (i == 0) {
                    ubicacion.append("/");
                } else {
                    ubicacion.append(d.getNombre()).append("/");
                }
            }
        }
        if (ubicacion.length() == 0) {
            ubicacion.append("/");
        }

        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) path.getLastPathComponent();
        Object objeto = nodo.getUserObject();

        if (objeto instanceof Archivo) {
            Archivo archivo = (Archivo) objeto;
            lblInfoNombre.setText("Nombre: " + archivo.getNombre());
            lblInfoTipo.setText("Tipo: Archivo");
            lblInfoUbicacion.setText("Ubicación: " + ubicacion.toString());
            lblInfoDetalles1.setText("Bloques: " + archivo.getTamanoEnBloques() + " | Primer BLK: " + archivo.getPrimerBloque());
            lblInfoDetalles2.setText("Propietario: " + archivo.getPropietario());
            String cadenaBloques = obtenerCadenaBloques(archivo.getPrimerBloque());
            lblInfoCadenaBLK.setText("Cadena: " + cadenaBloques);
        } else if (objeto instanceof Directorio) {
            Directorio dir = (Directorio) objeto;
            int numArchivos = dir.getArchivos().getSize();
            int numSubdirs = dir.getSubdirectorios().getSize();

            lblInfoNombre.setText("Nombre: " + dir.getNombre());
            lblInfoTipo.setText("Tipo: Directorio");
            String rutaDir = ubicacion.toString();
            if (path.getPathCount() > 1) {
                rutaDir = ubicacion.toString() + dir.getNombre() + "/";
            }
            lblInfoUbicacion.setText("Ruta: " + rutaDir);
            lblInfoDetalles1.setText("Archivos: " + numArchivos + " | Subdirectorios: " + numSubdirs);
            lblInfoDetalles2.setText("Propietario: " + dir.getPropietario());
            lblInfoCadenaBLK.setText("");
        } else {
            lblInfoNombre.setText("Seleccione un elemento");
            lblInfoTipo.setText("");
            lblInfoUbicacion.setText("");
            lblInfoDetalles1.setText("");
            lblInfoDetalles2.setText("");
            lblInfoCadenaBLK.setText("");
        }
    }

    private void mostrarDialogoCrearProceso() {
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        String[] operaciones;
        if (gestorArchivos.isModoAdministrador()) {
            operaciones = new String[] {"CREAR", "LEER", "ACTUALIZAR", "ELIMINAR"};
        } else {
            operaciones = new String[] {"LEER"};
        }
        
        gbc.gridx = 0; gbc.gridy = 0;
        panel.add(new JLabel("Operación:"), gbc);
        JComboBox<String> comboOperacion = new JComboBox<>(operaciones);
        gbc.gridx = 1; gbc.gridy = 0;
        panel.add(comboOperacion, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        JLabel lblArchivo = new JLabel("Archivo:");
        panel.add(lblArchivo, gbc);

        Lista<Archivo> archivos = gestorArchivos.obtenerTodosLosArchivos();
        String[] nombresArchivos = new String[archivos.getSize()];
        for (int i = 0; i < archivos.getSize(); i++) {
            nombresArchivos[i] = archivos.get(i).getNombre();
        }
        JComboBox<String> comboArchivo = new JComboBox<>(nombresArchivos);
        gbc.gridx = 1; gbc.gridy = 1;
        panel.add(comboArchivo, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        JLabel lblNombreNuevo = new JLabel("Nombre archivo:");
        panel.add(lblNombreNuevo, gbc);
        JTextField txtNombreArchivo = new JTextField("Archivo_" + System.currentTimeMillis() % 10000, 15);
        gbc.gridx = 1; gbc.gridy = 2;
        panel.add(txtNombreArchivo, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        JLabel lblBloques = new JLabel("Bloques:");
        panel.add(lblBloques, gbc);
        JSpinner spinnerBloques = new JSpinner(new SpinnerNumberModel(5, 1, 50, 1));
        gbc.gridx = 1; gbc.gridy = 3;
        panel.add(spinnerBloques, gbc);

        gbc.gridx = 0; gbc.gridy = 4; gbc.gridwidth = 1;
        JLabel lblDirectorio = new JLabel("Directorio destino:");
        panel.add(lblDirectorio, gbc);

        Lista<Directorio> directorios = gestorArchivos.obtenerTodosLosDirectorios();
        String[] nombresDirectorios = new String[directorios.getSize()];
        for (int i = 0; i < directorios.getSize(); i++) {
            Directorio dir = directorios.get(i);
            if (dir == gestorArchivos.getRaiz()) {
                nombresDirectorios[i] = "/ (raíz)";
            } else {
                nombresDirectorios[i] = dir.getNombre();
            }
        }
        JComboBox<String> comboDirectorio = new JComboBox<>(nombresDirectorios);
        gbc.gridx = 1; gbc.gridy = 4;
        panel.add(comboDirectorio, gbc);

        gbc.gridx = 0; gbc.gridy = 5; gbc.gridwidth = 2;
        JCheckBox chkAutoSimular = new JCheckBox("Iniciar simulación automáticamente", true);
        panel.add(chkAutoSimular, gbc);

        comboOperacion.addActionListener(e -> {
            String op = (String) comboOperacion.getSelectedItem();
            boolean esCrear = "CREAR".equals(op);

            lblArchivo.setVisible(!esCrear);
            comboArchivo.setVisible(!esCrear);
            lblNombreNuevo.setVisible(esCrear);
            txtNombreArchivo.setVisible(esCrear);
            lblBloques.setVisible(esCrear);
            spinnerBloques.setVisible(esCrear);
            lblDirectorio.setVisible(esCrear);
            comboDirectorio.setVisible(esCrear);

            panel.revalidate();
            panel.repaint();
        });

        if (gestorArchivos.isModoAdministrador()) {
            lblArchivo.setVisible(false);
            comboArchivo.setVisible(false);
            lblDirectorio.setVisible(true);
            comboDirectorio.setVisible(true);
        } else {
            lblArchivo.setVisible(true);
            comboArchivo.setVisible(true);
            lblNombreNuevo.setVisible(false);
            txtNombreArchivo.setVisible(false);
            lblBloques.setVisible(false);
            spinnerBloques.setVisible(false);
            lblDirectorio.setVisible(false);
            comboDirectorio.setVisible(false);
        }

        int result = JOptionPane.showConfirmDialog(this, panel, "Crear Proceso",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String opSeleccionada = (String) comboOperacion.getSelectedItem();
            Proceso.TipoOperacion tipoOp = Proceso.TipoOperacion.valueOf(opSeleccionada);

            if (tipoOp == Proceso.TipoOperacion.CREAR) {
                int dirIndex = comboDirectorio.getSelectedIndex();
                Directorio dirDestino = directorios.get(dirIndex);
                crearProcesoCrear(txtNombreArchivo.getText().trim(),
                        (Integer) spinnerBloques.getValue(),
                        dirDestino,
                        chkAutoSimular.isSelected());
            } else {
                if (comboArchivo.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this,
                            "No hay archivos disponibles para esta operación.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                crearProcesoSobreArchivo((String) comboArchivo.getSelectedItem(),
                        tipoOp,
                        chkAutoSimular.isSelected());
            }
        }
    }

    private void crearProcesoCrear(String nombreArchivo, int tamano, Directorio directorioDestino,
            boolean autoSimular) {
        if (nombreArchivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del archivo no puede estar vacío.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!disco.hayEspacio(tamano)) {
            JOptionPane.showMessageDialog(this,
                    "No hay suficiente espacio en disco para crear el archivo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String errorValidacion = gestorProcesos.validarOperacionArchivo(nombreArchivo, Proceso.TipoOperacion.CREAR);
        if (errorValidacion != null) {
            JOptionPane.showMessageDialog(this, errorValidacion, "Operación no permitida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Lista<Integer> bloquesLibres = disco.obtenerProximosBloquesLibres(tamano);
        if (bloquesLibres == null || bloquesLibres.getSize() < tamano) {
            JOptionPane.showMessageDialog(this,
                    "No se pudieron obtener los bloques necesarios.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Proceso proceso = gestorProcesos.crearProceso(
                "Crear_" + nombreArchivo,
                Proceso.TipoOperacion.CREAR,
                nombreArchivo,
                gestorArchivos.getUsuarioActual());

        proceso.setTamanoEnBloques(tamano);
        proceso.setDirectorioDestino(directorioDestino);

        for (int i = 0; i < bloquesLibres.getSize(); i++) {
            int bloqueReal = bloquesLibres.get(i);
            gestorProcesos.agregarSolicitudES(proceso, bloqueReal, Proceso.TipoOperacion.CREAR);
        }

        //actualizarTodo();

        if (autoSimular) {
            iniciarSimulacionAutomatica();
        }

        String nombreDir = (directorioDestino == gestorArchivos.getRaiz()) ? "/ (raíz)" : directorioDestino.getNombre();
        JOptionPane.showMessageDialog(this,
                "Proceso CREAR creado para: " + nombreArchivo + " (" + tamano + " bloques)\n" +
                        "Directorio destino: " + nombreDir + "\n" +
                        "Bloques asignados: " + bloquesToString(bloquesLibres),
                "Proceso Creado", JOptionPane.INFORMATION_MESSAGE);
    }

    private void crearProcesoSobreArchivo(String nombreArchivo, Proceso.TipoOperacion operacion, boolean autoSimular) {
        String errorValidacion = gestorProcesos.validarOperacionArchivo(nombreArchivo, operacion);
        if (errorValidacion != null) {
            JOptionPane.showMessageDialog(this, errorValidacion, "Operación no permitida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Archivo archivo = gestorArchivos.buscarArchivoEnSistema(nombreArchivo);
        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo: " + nombreArchivo,
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Lista<Integer> bloques = disco.obtenerCadenaBloquesArchivo(archivo.getPrimerBloque());

        String nombreProceso;
        String mensaje;
        switch (operacion) {
            case LEER:
                nombreProceso = "Leer_" + archivo.getNombre();
                mensaje = "Proceso LEER creado para: " + archivo.getNombre();
                break;
            case ACTUALIZAR:
                nombreProceso = "Actualizar_" + archivo.getNombre();
                mensaje = "Proceso ACTUALIZAR creado para: " + archivo.getNombre();
                break;
            case ELIMINAR:
                nombreProceso = "Eliminar_" + archivo.getNombre();
                mensaje = "Proceso ELIMINAR creado para: " + archivo.getNombre();
                break;
            default:
                nombreProceso = "Op_" + archivo.getNombre();
                mensaje = "Proceso creado para: " + archivo.getNombre();
        }

        Proceso proceso = gestorProcesos.crearProceso(
                nombreProceso,
                operacion,
                archivo.getNombre(),
                gestorArchivos.getUsuarioActual());

        gestorProcesos.agregarSolicitudesParaArchivo(proceso, bloques, operacion);

        //actualizarTodo();

        if (autoSimular) {
            iniciarSimulacionAutomatica();
        }

        JOptionPane.showMessageDialog(this, mensaje, "Proceso Creado", JOptionPane.INFORMATION_MESSAGE);
    }

    private void crearMultiplesProcesos(int cantidad) {
        int procesosCreados = 0;
        for (int i = 0; i < cantidad; i++) {
            try {
                crearProcesoPrueba(false);
                procesosCreados++;
                Thread.sleep(10);
            } catch (Exception ex) {
            }
        }

        //actualizarTodo();

        if (procesosCreados > 0) {
            iniciarSimulacionAutomatica();
        }

        JOptionPane.showMessageDialog(this,
                procesosCreados + " procesos creados.\nSimulación iniciada automáticamente.",
                "Procesos Creados", JOptionPane.INFORMATION_MESSAGE);
    }

    private void crearProcesoPrueba(boolean mostrarDialogos) {
        Lista<Archivo> archivos = gestorArchivos.obtenerTodosLosArchivos();

        if (gestorArchivos.isModoAdministrador() && Math.random() < 0.20) {
            crearDirectorioAleatorio();
        }

        Proceso.TipoOperacion[] operaciones;
        if (gestorArchivos.isModoAdministrador()) {
            operaciones = new Proceso.TipoOperacion[] {
                    Proceso.TipoOperacion.CREAR,
                    Proceso.TipoOperacion.LEER,
                    Proceso.TipoOperacion.ACTUALIZAR,
                    Proceso.TipoOperacion.ELIMINAR
            };
        } else {
            operaciones = new Proceso.TipoOperacion[] {
                    Proceso.TipoOperacion.LEER
            };
        }

        int opIndex = (int) (Math.random() * operaciones.length);
        Proceso.TipoOperacion operacion = operaciones[opIndex];

        if (operacion == Proceso.TipoOperacion.CREAR) {
            Directorio directorioDestino = seleccionarDirectorioAleatorio();
            String nombreArchivo = "Archivo_" + System.currentTimeMillis() % 10000;
            int tamano = 3 + (int) (Math.random() * 6);

            if (!disco.hayEspacio(tamano)) {
                return;
            }

            String errorValidacion = gestorProcesos.validarOperacionArchivo(nombreArchivo, operacion);
            if (errorValidacion != null) {
                return;
            }

            Lista<Integer> bloquesLibres = disco.obtenerProximosBloquesLibres(tamano);
            if (bloquesLibres == null || bloquesLibres.getSize() < tamano) {
                return;
            }

            Directorio dirActualAnterior = gestorArchivos.getDirectorioActual();
            gestorArchivos.setDirectorioActual(directorioDestino);

            Proceso proceso = gestorProcesos.crearProceso(
                    "Crear_" + nombreArchivo,
                    Proceso.TipoOperacion.CREAR,
                    nombreArchivo,
                    gestorArchivos.getUsuarioActual());

            proceso.setTamanoEnBloques(tamano);
            proceso.setDirectorioDestino(directorioDestino);

            for (int i = 0; i < bloquesLibres.getSize(); i++) {
                int bloqueReal = bloquesLibres.get(i);
                gestorProcesos.agregarSolicitudES(proceso, bloqueReal, Proceso.TipoOperacion.CREAR);
            }

            gestorArchivos.setDirectorioActual(dirActualAnterior);
            return;
        }

        if (archivos.isEmpty()) {
            return;
        }

        Lista<Archivo> archivosDisponibles = new Lista<>();
        for (int i = 0; i < archivos.getSize(); i++) {
            Archivo arch = archivos.get(i);
            if (!gestorProcesos.hayEliminacionPendiente(arch.getNombre())) {
                archivosDisponibles.insertarFinal(arch);
            }
        }

        if (archivosDisponibles.isEmpty()) {
            return;
        }

        int index = (int) (Math.random() * archivosDisponibles.getSize());
        Archivo archivo = archivosDisponibles.get(index);

        Lista<Integer> bloques = disco.obtenerCadenaBloquesArchivo(archivo.getPrimerBloque());

        String nombreProceso;
        switch (operacion) {
            case LEER:
                nombreProceso = "Leer_" + archivo.getNombre();
                break;
            case ACTUALIZAR:
                nombreProceso = "Actualizar_" + archivo.getNombre();
                break;
            case ELIMINAR:
                nombreProceso = "Eliminar_" + archivo.getNombre();
                break;
            default:
                nombreProceso = "Op_" + archivo.getNombre();
        }

        Proceso proceso = gestorProcesos.crearProceso(
                nombreProceso,
                operacion,
                archivo.getNombre(),
                gestorArchivos.getUsuarioActual());

        gestorProcesos.agregarSolicitudesParaArchivo(proceso, bloques, operacion);
    }

    private void crearDirectorioAleatorio() {
        String[] nombresDirectorios = {"Documentos", "Imagenes", "Videos", "Musica", "Descargas",
                "Proyectos", "Trabajo", "Personal", "Backup", "Temporal"};

        String nombreBase = nombresDirectorios[(int) (Math.random() * nombresDirectorios.length)];
        String nombreDir = nombreBase + "_" + (System.currentTimeMillis() % 1000);

        Directorio dirPadre = seleccionarDirectorioAleatorio();

        Directorio dirActualAnterior = gestorArchivos.getDirectorioActual();

        gestorArchivos.setDirectorioActual(dirPadre);
        boolean modoAnterior = gestorArchivos.isModoAdministrador();
        gestorArchivos.setModoAdministrador(true);
        gestorArchivos.crearDirectorio(nombreDir);
        gestorArchivos.setModoAdministrador(modoAnterior);

        gestorArchivos.setDirectorioActual(dirActualAnterior);

        //actualizarArbol();
    }

    private Directorio seleccionarDirectorioAleatorio() {
        Lista<Directorio> todosDirectorios = gestorArchivos.obtenerTodosLosDirectorios();

        if (todosDirectorios.isEmpty()) {
            return gestorArchivos.getRaiz();
        }

        int index = (int) (Math.random() * todosDirectorios.getSize());
        return todosDirectorios.get(index);
    }

    private void iniciarSimulacionAutomatica() {
        if (!simulacionActiva) {
            simulacionActiva = true;
            timerSimulacion.start();
            btnSimular.setText("⏹ Detener");
        }
    }

    private String bloquesToString(Lista<Integer> bloques) {
        if (bloques == null || bloques.isEmpty()) {
            return "[]";
        }
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < bloques.getSize(); i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(bloques.get(i));
        }
        sb.append("]");
        return sb.toString();
    }

    // ========== MAIN ==========
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear10Procesos;
    private javax.swing.JButton btnCrearDirectorio;
    private javax.swing.JButton btnCrearProceso;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JToggleButton btnModoAdmin;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox<String> comboPlanificador;
    private javax.swing.JLabel lblCabezaDisco;
    private javax.swing.JLabel lblEstadoDisco;
    private javax.swing.JLabel lblInfoCadenaBLK;
    private javax.swing.JLabel lblInfoDetalles1;
    private javax.swing.JLabel lblInfoDetalles2;
    private javax.swing.JLabel lblInfoNombre;
    private javax.swing.JLabel lblInfoTipo;
    private javax.swing.JLabel lblInfoUbicacion;
    private javax.swing.JLabel lblMovimientosTotales;
    private javax.swing.JLabel lblPlanificador;
    private javax.swing.JLabel lblPlanificadorActual;
    private javax.swing.JLabel lblPromedioMovimientos;
    private javax.swing.JLabel lblSolicitudesAtendidas;
    private javax.swing.JLabel lblSolicitudesPendientes;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JPopupMenu menuContextual;
    private javax.swing.JMenuItem menuCrearArchivo;
    private javax.swing.JMenuItem menuCrearDir;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuRenombrar;
    private javax.swing.JPanel panelArbol;
    private javax.swing.JPanel panelBotonesProcesos;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelDiscoContainer;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JScrollPane scrollArbol;
    private javax.swing.JScrollPane scrollAsignacion;
    private javax.swing.JScrollPane scrollColaIO;
    private javax.swing.JScrollPane scrollFAT;
    private javax.swing.JScrollPane scrollProcesos;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JSlider sliderVelocidad;
    private javax.swing.JSplitPane splitCentral;
    private javax.swing.JSplitPane splitIzquierdo;
    private javax.swing.JSplitPane splitPrincipal;
    private javax.swing.JSplitPane splitProcesos;
    private javax.swing.JTable tableAsignacion;
    private javax.swing.JTable tableColaIO;
    private javax.swing.JTable tableFAT;
    private javax.swing.JTable tableProcesos;
    private javax.swing.JTree treeArchivos;
    // End of variables declaration//GEN-END:variables
}
